language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t alexhod/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexhod/docker-react npm run test
    